services:
  postgres:
    image: postgres:15
    container_name: board-game-db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: linux1234
      POSTGRES_DB: game_db
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data

  mongodb:
    image: mongo:latest
    container_name: board-game-mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: linux1234
    ports:
      - "27017:27017"
    volumes:
      - ./data/mongo:/data/db

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
